### ISSUE TITLE
Microclima bugs and issues

### ISSUE THREAD

**Issue by mattmar** [ilyamaclean/microclima#11]
[dem1k_clipped.zip](https://github.com/ilyamaclean/microclima/files/3872753/dem1k_clipped.zip)

## Which operating system are you running?

Linux -- Ubuntu 18.04

## Which version of R are you using?

3.6.1

## What is the problem?

The runauto function fails with coastal=TRUE, with this error:

> Direction: 135 degrees 
> Direction: 180 degrees 
> Direction: 225 degrees 
> Direction: 270 degrees 
> Direction: 315 degrees 
> Computing mean coastal exposure of ncep grid cell 
> Adjusting coastal exposure by ncep means 
> Downloading sea-surface temperature data 
> Applying coastal effects 
> Error in acoast[xi, yi, ] : subscript out of bounds
> Calls: <Anonymous> -> micro_ncep -> <Anonymous>

## How can we reproduce this? Which functions have you used and with which datasets and parameters?
This is my code:
microclima::runauto(dem1kmr, dstart="01/01/2016", dfinish="01/03/2016", hgt = 0.5,
                             l = NA, x = NA, coastal = TRUE, r.is.dem=TRUE, mesoresolution=500,
                             habitat = 14, plot.progress = FALSE, save.memory=TRUE)

I am attaching the dem raster file I use to define extent and resolution.
Thank you

**Comment by ilyamaclean** [comment]
Thank you for reporting this bug. The issue was partly caused by the requirement that the x, y and z units of the supplied raster are the same to enable accurate calculation of slope angles etc. Grid cells should also be square.  Try using get_dem() to retrieve a dem of your study area.

Please not also that NA values are assumed to be sea – important in the calculation of coastal effects
I’ve updated the help files to make this clear, and have also traced a couple of additional bugs that were causing issues. Please let me know if problems persist.
